### ISSUE TITLE
building SW error

### ISSUE THREAD

**Issue by 9a4db** [kantooon/qradiolink#1]
Hello, in accordance to instructions reporting build error here
ubuntu 17.04

q@q-X756UX:~/qradiolink/build$ qmake-qt4 ..
q@q-X756UX:~/qradiolink/build$ make
/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../mainwindow.ui -o ui_mainwindow.h
make: /usr/lib/x86_64-linux-gnu/qt4/bin/uic: Command not found
Makefile:511: recipe for target 'ui_mainwindow.h' failed
make: *** [ui_mainwindow.h] Error 127
q@q-X756UX:~/qradiolink/build$ 

73
Djani

**Comment by kantooon** [comment]
Hi Djani,
It seems like your qt4 user interface compiler is missing. I suggest checking that you have the QT4 devel packages installed.
Cheers,
Adrian

**Comment by kantooon** [comment]
Any updates? If there are none, I will close this issue as "can't reproduce"
