### ISSUE TITLE
Add PTT control on RS232 port

### ISSUE THREAD

**Issue by andrew771211** [kantooon/qradiolink#21]
In order to control an external relay to switch RX/TX port, should be useful that the ptt button triggers a output command to the RS232 port 
thanks

**Comment by kantooon** [comment]
Will be done at some time, but I think using USB or I2C. RS232 is too bulky and nowhere to be found on modern devices.

**Comment by kantooon** [comment]
For now you can use the GPIO pins exposed by the USRP if you have such equipment.

**Comment by andrew771211** [comment]
Thanks,
I have bladeRF, I will check

**Comment by kantooon** [comment]
Look at https://github.com/pavel-a/usb-relay-hid
I'm going to add support for this type of relays first. Add other hardware suggestion to the comments here.
