### ISSUE TITLE
Audio Selection

### ISSUE THREAD

**Issue by Radiomix2000** [kantooon/qradiolink#47]
There is not possible to choose custom audio device. 
Would be good to add such option.

**Comment by kantooon** [comment]
You can choose any device using the pavucontrol application (playback and recording). Or do you mean something else?

**Comment by Radiomix2000** [comment]
No, I mean to choose in application the audiocard, which is not system default. I'm have 2 audiocards in my pc, and one is used only for radiocoms, digi modes, digivoice etc.. and other is used just as system default for listening to music and films.

**Comment by kantooon** [comment]
So you're not using Pulseaudio? I have some Alsa code borrowed from another project, but it's not enabled by default. Are you looking at using Alsa directly?

**Comment by kantooon** [comment]
Oh. I see what you mean, to choose within the application. Ok, I'll put it on the list.

**Comment by kantooon** [comment]
![qradiolink48](https://user-images.githubusercontent.com/968724/66191692-940f6d80-e697-11e9-9c85-cfa0b5054a0b.png)

This is what Pulseaudio devices look like under the new audio backend.

**Comment by kantooon** [comment]
In release 0.8.1-4

**Comment by kantooon** [comment]
I should mention that starting with 0.8.2 it's no longer necessary to restart the application to change audio device. The audio threads are restarted when changing the device in settings.
